Authoritative timing across trigger sources [semver:major] (#112)
Co-authored-by: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Co-authored-by: David Beitey <david@davidjb.com>
Co-authored-by: Pedro Chambino <pchambino@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -63,7 +63,7 @@ jobs:
           name: Import Tests using BATS
           command: |
             export BATS_IMPORT_DEV_ORB="eddiewebb/<<pipeline.parameters.orbname>>@dev:<<pipeline.number>>"
-            bats test            
+            bats --jobs 8 test            
       - pr-comment
       - run:
           name: Check Semver
@@ -81,29 +81,35 @@ jobs:
 
   publish:
     docker:
-      - image: cimg/base:2019.08
+      - image: cimg/base:2024.01
     working_directory: ~/repo
     steps:
       - checkout
       - install-circleci   
       - pr-info  
-      - run:
-          name: Promote to prod
-          command: |
-            SEMVER_INCREMENT=`git log -1 --pretty=%B | sed -En 's/.*\[semver:(major|minor|patch|skip)\].*/\1/p'`
-            if [ -z ${SEMVER_INCREMENT} ];then
-              echo "Merge commit did not indicate which SemVer increment to make. Please ammend commit with [semver:FOO] where FOO is major, minor, or patch"
-              exit 1
-            elif [ "$SEMVER_INCREMENT" == "skip" ];then
-              echo "SEMVER in commit indicated to skip orb release"
-              echo "export PR_MESSAGE=\"Orb publish was skipped due to [semver:skip] in commit message.\""  >> $BASH_ENV
-              exit 0
-            else
-              PUBLISH_MESSAGE=`circleci orb publish promote eddiewebb/<<pipeline.parameters.orbname>>@dev:<<pipeline.number>> ${SEMVER_INCREMENT} --token ${CIRCLECI_API_KEY}`            
-              echo $PUBLISH_MESSAGE
-              ORB_VERSION=$(echo $PUBLISH_MESSAGE | sed -n 's/Orb .* was promoted to `\(.*\)`.*/\1/p')
-              echo "export PR_MESSAGE=\"BotComment: *Production* version of orb available for use - \\\`${ORB_VERSION}\\\`\"" >> $BASH_ENV
-            fi
+      - when:
+          condition:
+            or:
+              - equal: [ trying, << pipeline.git.branch >> ]
+              - equal: [ staging, << pipeline.git.branch >> ]
+          steps:
+            - run:
+                name: Promote to prod
+                command: |
+                  SEMVER_INCREMENT=`git log -1 --pretty=%B | sed -En 's/.*\[semver:(major|minor|patch|skip)\].*/\1/p'`
+                  if [ -z ${SEMVER_INCREMENT} ];then
+                    echo "Merge commit did not indicate which SemVer increment to make. Please ammend commit with [semver:FOO] where FOO is major, minor, or patch"
+                    exit 1
+                  elif [ "$SEMVER_INCREMENT" == "skip" ];then
+                    echo "SEMVER in commit indicated to skip orb release"
+                    echo "export PR_MESSAGE=\"Orb publish was skipped due to [semver:skip] in commit message.\""  >> $BASH_ENV
+                    exit 0
+                  else
+                    PUBLISH_MESSAGE=`circleci orb publish promote eddiewebb/<<pipeline.parameters.orbname>>@dev:<<pipeline.number>> ${SEMVER_INCREMENT} --token ${CIRCLECI_API_KEY}`            
+                    echo $PUBLISH_MESSAGE
+                    ORB_VERSION=$(echo $PUBLISH_MESSAGE | sed -n 's/Orb .* was promoted to `\(.*\)`.*/\1/p')
+                    echo "export PR_MESSAGE=\"BotComment: *Production* version of orb available for use - \\\`${ORB_VERSION}\\\`\"" >> $BASH_ENV
+                  fi
       - pr-comment
 
 
@@ -130,7 +136,8 @@ commands:
       - run: 
           name: Install CircleCI CLI (the new one)
           command: |
-            curl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh --fail --show-error | bash
+            #curl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh --fail --show-error | bash
+            circleci update
             circleci version
             echo "Run circleci help"              
             circleci help
@@ -141,7 +148,7 @@ commands:
       - run:
           name: Pack and Validate
           command: |
-            circleci config pack src/ > packed.yml
+            circleci orb pack src > packed.yml
             circleci orb validate packed.yml
   pr-comment:
     description: add message to pr this build originated from
